import React,{useContext, useEffect, useState,Suspense} from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'
import Loading from '../components/loading/loading'
// import Search from '../components/search/search'


const Router = dynamic(() => import('../router/index'),{
  loading:() => <Loading />
})

import TostMessage from '../components/tost/tostMessage'

export default function Home() {
  
  
  

  return (
    <div>
    <Head>
        <title >Tdtu Ilmiy bo'limi</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <TostMessage />
        {/* <Loading /> */}
        <Suspense fallback={<Loading />} >
        <Router />
        </Suspense>
      

      </main>
    </div>
  )
}
